[google_service_account]
type= "service_account"
project_id= "samelimu"
private_key_id= "592985dd8eae884c2d8b3b35bf3f77d9ef9be6fb"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFzODGR9SfeWT4\nEWOef+sDED6hyGdhV8kyWrZiNJyLDYRBqJL8hjk4qZ7MS02FJgxPsBISt2ZflkcS\ndcba6cTpp7+1S6nJV7pWSTlqxMpQ0NeHOM7mGqaqb1MqojRLmk0JxhB806QrYBzv\nrgmOEaZgEeDn4opzKVdZeVmro0Nv67aU3WBkWBmCO+q+ZhWnxuv2Ei+qEKiKwPid\nED5yYGFEiHKpJmNdEM/3fd7ucHXreQx7cDIUITUTzbHZWwhMq8+BdkEOGmzimzs2\nOHmlwyieWVEGyfXgw8p1SMrtZDgLKTD9N2HonatPM2MIqB/9T7E9O3NgLXAK+nrZ\ndhTzzUOvAgMBAAECggEADVaUJGAc+Gaz5lPV3I79BrHbvLEfjN2Mlbau7Hm7wgIL\n/xl3qqD/ztBcAvljpYI7+6EAjFPjCrhphoHRV7BtNOG4+GgSb59Y02S7WHXOEXEO\nd5yJvH6OP+6jNGbHu/67CdkErPDgoIQqBLI/DAjTUqXMqBZgsQStUpKaTLavtNDu\nZH1W5rZu7PaPpVY09CizwW3rxsCpN9MQnzZczU5EFSaX9SGXSVs7hY6dDG/To7pR\nAMXhQlvwEX5yY8BUmGAmKvSd8keqBCDEJ7dSve7IURehzaNiKqUJVfLqXLkEZejK\n8RurO1D6kndPb6knMrCidEi1eIy3Cgh++XdObRbgcQKBgQD+k9i1I2tl17GAKdTa\n4ADCtV7TpY4ZTf43aWBF8uLX9NeIqNweN/bzkZehdQgw2mO0mLDwQq9RooQdJXgt\nR029HFWgnEvwo7U1BSCcpxtyv4n85NMmO4gAAHVcK+JZ/qIyvgZKtmA3ZLYsvF+h\nqdkJb0iH4A5pP542+R4JbviWhQKBgQDG59Dq0O6Jrz5DvIHN2xpkcmHh6A/Jtz3E\nMrQaHXRDyzEGDctE74HsufaeJughVQPsO3qrWQqPXXJKi1V+LjiUqt10wQj5iQAJ\nVJ0RylD/hcJg13plBNwYmeKDq1Z5DBxbjdw6DM6MPS1uvXpC3PQ21Oj4ewNIrBtK\nInsKESvJowKBgQDyutcaRu5EyXbFo5z/ICu5eqMym5y0RegIv2F68E4X6KyE8bQG\n4AeHTx9LY8HuipwceqXiP0LYTGM5Qxul2GGn2VdPbxb9F6pUJlJk6vRB4ZzY0vj8\ncDCJB+befj0w35eZWBO5stBkoJMOboGkK8TzuPZoD1rOQUlCUx6vke5V3QKBgHj/\n9LukNjhT/xC90EkmjLumSZ1fyprvegeswJtSZ7QGG+CO66UX/nW/+yLikDwWt7gx\nxsIN/LqSIkDu2idUft8Rwn6QH6GNkhQbASIdbYDEIic/bhmeBzaABqgKxyQEFgws\nFFjMCaqOXOENKx8ZwwbIJqFiU/EVodRLfYX2RCj5AoGBAN/So0kpH4G4A9EUYgT9\nZ8+bCygXMHOJqBhExOZYQrUudCg5KN9yuAcUtIacM0C3PsRc54ciewjuYg3GuomI\nGtD2HDXPfkJeSCO814tZtb5KtMfvIlkb3SPIANso0HUVfbuN2AJ4h/d8KS+UIkO/\nzGyIg0JFl46bmkWLbSEbQOGg\n-----END PRIVATE KEY-----\n"
client_email= "samhighschoolreports@samelimu.iam.gserviceaccount.com"
client_id= "110116822381437527517"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/samhighschoolreports%40samelimu.iam.gserviceaccount.com"
universe_domain= "googleapis.com"

[google_drive_files]
team_kathy = "1dutx00NcPKenFat2G09r-azauvZhy_z-"      # Team Kathy Results.xlsx file ID
team_kelly = "124Xm9l-fu7J1e0678VGgokhIITE8IEwK"       # Team Kelly A. Results.xlsx file ID
team_lissette = "1APTBwNbvdeMZFidHuZ5pm5eKWaKRRbNs"    # Team Lissette A.Results.xlsx file ID
high_school_data = "REPLACE_WITH_ACTUAL_FILE_ID" # High School Data Sheet.xlsx file ID - UPLOAD TO DRIVE FIRST

# Note: Logo is now loaded from local file "SAM Elimu Logo-white_edited.png" - no Drive upload needed

# Instructions:
# 1. Get your service account JSON file from Google Cloud Console
# 2. Copy all values from the JSON file to the corresponding fields above
# 3. Get Google Drive file IDs by opening files in Drive and copying ID from URL
# 4. Share each file with your service account email (found in client_email field)
# 5. Ensure "SAM Elimu Logo-white_edited.png" is in the same directory as streamlit_app.py
# 5. Save this file as .streamlit/secrets.toml (remove .example from filename)
# 6. Never commit the actual secrets.toml file to git!
